### ISSUE TITLE
Create Makefile pipeline for paper

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/pheval#12]
Using best practice Makefile standards as we have discussed (one goal per file, declared phony goals etc) create a Makefile that runs  the following:

- [x] Merge mp and hp.owl to mp-hp.owl with ROBOT
- [x] Using mp-hp.owl, generate a semantic similarity profile (SEM1) (NOTE this could take hours, if not a day)
- [x] Manipulate hp.owl and generate a second semantic similarity profile (SEM2)
- [x] Finish `pheval-utils scramble-semsim` which takes as an input a semantic similarity profile such as SEM1, one or more column names, scrambles it according to some scramble factor, and output its again, scrambled. The input and output have the exact same columns, and same number of rows. The only thing that changes is values in the columns selecting for scrambling.
- [x] In the makefile, scramble SEM1 and SEM2 separately 3 times. SEM1.1, SEM1.2, SEM1.3, SEM2.1, SEM2.2, SEM2.3. There should be one Makefile goal for each of these, calling `pheval-utils scramble-semsim`, so 6 separate makefile goals.
- [x] Add a pheval-utils method `semsim-convert` which converts 1 semsim table to EXOMISER format (whatever is used in the table)
- [x] Generate 6 different Exomiser databases based on the six semsim tables generated above
- [x] use `pheval-utils scramble-phenopackets` to generate 4 variations of the entire phenopacket corpus
- [x] Run `pheval run` with exomiser on all six inputs (databases) over all 4 variations, so 4*6=24 runs.
- [x] Run `pheval run` with an old version of exomiser over one of the databases over all 4 corpora
- [x] Run `pheval run` with phentogene over all 4 corpora.
- [x] Run `pheval analyse` to create a simple (really super trivial) report of how ranks changed across runs.

**Comment by yaseminbridges** [comment]
Along with the scramble phenopackets, there needs to be a spike vcf and an update phenopacket method
