### ISSUE TITLE
Implement support for disease prioritisation

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval#131]
We can currently benchmark the performance of gene/variant prioritisation tools and the corresponding results. Damian has asked me to set up a runner for L4CI - documentation here: https://thejacksonlaboratory.github.io/L4CI/index.html 

Disease prioritisation can also be assessed for LIRICAL and Exomiser if it is of interest and should be quite easy to implement.

- [x] #134
- [x] #138
- [x] #162
- [x] #165

**Comment by matentzn** [comment]
I think in all generality it is a good idea to add "disease prioritisation" (a fancy term for diagnosis?) to results model etc! I would like to understand (no need to type) how that exactly differs from normal phenotype prioritisation. From a high level, single sentence perspective :D
