### ISSUE TITLE
Implement support within analysis methods for disease matching

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval#165]
In the interest of speed, @julesjacobsen is fine with me implementing the disease matching the "quick" way, ultimately resulting in working but duplicated code. I will go in at a later time and refactor the analysis methods to make them more generalisable across the variant/gene/disease matching but this is a longer job.

**Comment by matentzn** [comment]
Can you say a few more things about this? What exactly will you implement where? What do you mean by "disease matching"?

**Comment by yaseminbridges** [comment]
Adding to what @julesjacobsen said, it will be implemented in the analysis scripts i.e., all of the scripts in the `analysis` directory barring the `rank_stats.py`.

**Comment by matentzn** [comment]
Do I understand it correctly that the matching itself will be implemented in Exomiser, and this here issue is about evaluating  `Phenotype to Disease ranking` if a tool supports them?

**Comment by yaseminbridges** [comment]
No, this needs to be implemented here in PhEval. What I mean by "matching" is that the known diseases are extracted from the phenopacket and then compared to the tool output (`pheval_disease_results`), noting the ranks for found diseases and producing the summary outputs (top, top3, top5....)
