### ISSUE TITLE
Correct typos in 'About' documentation

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/pheval#167]
**Where:** https://monarch-initiative.github.io/pheval/about/
**What:**  Dear wonderful team. I'd like to kindly offer a suggestion to correct a few typos in the 'About' paragraph of your documentation page. I have entered a suggestion for an updated version below. Please let me know if I need to provide any additional information.

`Many variant prioritization tools (such as [Exomiser](https://exomiser.readthedocs.io/) and other computational approaches) rely on ontologies and phenotype matching, sometimes involving complex processes such as cross-species inference. The performance of such tools is exceedingly hard to evaluate because of the many factors involved: changes to the structure of the ontology, cross-species mappings, and semantic similarity algorithms can have significant consequences. Furthermore, the lack of suitable real-world problems/corpora leads to the situation that many algorithms are evaluated using simulations, which may fail to capture real-world scenarios. The lack of an evaluation framework that enables studying effects on data and knowledge inputs on real-world problems makes it difficult to optimize algorithms. To this end, we are developing a modular Phenotypic Inference Evaluation Framework (PhEval), which is delivered as a community resource.`

**Comment by souzadevinicius** [comment]
https://monarch-initiative.github.io/pheval/about/
