### ISSUE TITLE
Create new Repo for managing the Monarch PhEval config

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#172]
Right now, the pheval repo and the config are both in the same repo. We should

1. Have a repo with just the config (pheval-monarch-pipeline) and an easy way to update it
2. Have the config in the main pheval be some small test config we can run as part of continuous integration

**Comment by souzadevinicius** [comment]
https://github.com/souzadevinicius/monarch-pheval

**Comment by souzadevinicius** [comment]
https://github.com/souzadevinicius/monarch-pheval
