### ISSUE TITLE
Create pseudo runner for PhEval testing

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#173]
To run a full PhEval run in CI, we need a simple runner implementation (in pheval framework) we can use to simulate a run without having any serious dependencies. The runner should do _some stuff_, like reading this the files, running the results etc, but nothing sophisticated.

This issue is done when

- [x] We have a pseudo runner implementation
- [x] We have a GitHub action that simulates a framework run when a PR is made.

**Comment by souzadevinicius** [comment]
https://github.com/monarch-initiative/pheval/issues/337
