### ISSUE TITLE
Add semsim-comparison percentage-diff metadata columns

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/pheval#190]
The current semsim-comparison percentage-diff file encodes metadata file as column name like this:

| subject_id | object_id  | phenio-hp-hp.semsimian.0.7_jaccard_similarity | upheno1-hp-hp.semsimian.0.7_jaccard_similarity | diff  |
|------------|------------|-----------------------------------------------|------------------------------------------------|-------|
| HP:0010136 | HP:0010147 |                            0.8021978021978022 |                             0.8823529411764706 | 9.99% |
| HP:0010147 | HP:0010136 |                            0.8021978021978022 |                             0.8823529411764706 | 9.99% |
| HP:0008060 | HP:0007750 |                            0.8524590163934426 |                                         0.9375 | 9.98% |
| HP:0007750 | HP:0008060 |                            0.8524590163934426 |                                         0.9375 | 9.98% |

It needs to be replaced to this:

| subject_id | object_id  | jaccard_similarity_left | jaccard_similarity_right | diff  | left_file                  | right_file                  |
|------------|------------|-------------------------|--------------------------|-------|----------------------------|-----------------------------|
| HP:0010136 | HP:0010147 |      0.8021978021978022 |       0.8823529411764706 | 9.99% | phenio-hp-hp.semsimian.0.7 | upheno1-hp-hp.semsimian.0.7 |
| HP:0010147 | HP:0010136 |      0.8021978021978022 |       0.8823529411764706 | 9.99% | phenio-hp-hp.semsimian.0.7 | upheno1-hp-hp.semsimian.0.7 |
| HP:0008060 | HP:0007750 |      0.8524590163934426 |                   0.9375 | 9.98% | phenio-hp-hp.semsimian.0.7 | upheno1-hp-hp.semsimian.0.7 |
| HP:0007750 | HP:0008060 |      0.8524590163934426 |                   0.9375 | 9.98% | phenio-hp-hp.semsimian.0.7 | upheno1-hp-hp.semsimian.0.7 |

**PS: Some stats**

A file with **265829** lines had its size increased from **16MB** using the first template to **30MB** compared to the second one.

**Comment by matentzn** [comment]
Thank you @souzadevinicius I am not sure what is the right answer. I reached out for other opinions. Maybe your original solution (solution 1) is actually preferable after all if the file size increase is so enormous. On the other hand, maybe adding a column compresses well? These 16MB and 30MB files, if you gzip them, what is their difference?

**Comment by souzadevinicius** [comment]
Replaced by this approach

https://github.com/monarch-initiative/monarch-semantic-similarity-profiles/issues/9

**Comment by souzadevinicius** [comment]
Replaced by this approach
https://github.com/monarch-initiative/monarch-semantic-similarity-profiles/issues/9
