### ISSUE TITLE
change version in 'poetry add pheval' so Pheval contains PhevalDiseaseResult

### ISSUE THREAD

**Issue by iQuxLE** [monarch-initiative/pheval#266]
Currently when going though the documentation of Pheval to create a runner and adding pheval to poetry it adds version **0.2.0**

```
❯ poetry add pheval
Creating virtualenv exomiser-rag-embedding-runner-rrKu6h-f-py3.11 in /Users/carlo/Library/Caches/pypoetry/virtualenvs
Using version ^0.2.0 for pheval
```

However this version does not contain the `PhevalDiseaseResult` class.
An import from`pheval.post_processing.post_processing` should contain `PhevalDiseaseResult`

The weird thing is that I checked with `pheval.exomiser `runner and its version is `pheval 0.1.0` (https://github.com/monarch-initiative/pheval.exomiser). This contains the PhevalDiseaseResult via the same named import from `pheval.post_processing.post_processing`.

Edit: Permalink to pheval.exomiser post_process.py:
https://github.com/monarch-initiative/pheval.exomiser/blob/d742abbde1a5c870b91e462320edbf469c4bd4e8/src/pheval_exomiser/post_process/post_process_results_format.py#L5-L10

**Comment by yaseminbridges** [comment]
Add PhEval with this command:

`poetry add git+https://github.com/monarch-initiative/pheval.git`

The PyPi release is not updated

**Comment by matentzn** [comment]
@souzadevinicius is there a documentation page "How to create a new PhEval release" on pypi? 

Better not be spreading the `poetry add git+https://github.com/monarch-initiative/pheval.git` for downstream repos..
