### ISSUE TITLE
Add handling of chromosome naming in the phenopacket

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval#307]
The new phenopackets in the phenopacket store define the chromosome position of the variant as either "chr1" or "1". Should implement handling in the codebase that removes the "chr" for proper matching to the results

**Comment by matentzn** [comment]
Should this not always be done the same way in phenopackets? Is this because the standard changed recently?

**Comment by yaseminbridges** [comment]
The phenopacket schema is pretty broad on this I think - it says it in the documentation that the `chrom` field can either be a chromosome or contig identifier. The original LIRICAL phenopackets just had it as 1-22, X & Y but the new ones in the phenopacket store are chr1-22, chrX & chrY. It will be pretty easy to handle this in the code

**Comment by yaseminbridges** [comment]
I understand what you mean now, I will bring it up to Jules!
