### ISSUE TITLE
Add check for ref and alt alleles for variants recorded in a phenopacket

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval#370]
There needs to be a check implemented for variants in the phenopacket to ensure the reference and alternate alleles are different. If the two are the same an error will be thrown downstream for tools that use VCF if the spiking VCF command is used in PhEval to generate.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify VcfSpiker class to check for identical reference and alternate alleles and raise an error if found. Update corresponding test cases.

You can review changes in this commit: https://github.com/mnmnk43434/monarch-initiative-pheval-370/commit/649a5c5812cc7997094e81246659c86d5cc356e5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
