### ISSUE TITLE
Generate semantic similarity test data for implementing the utility methods

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#39]
Try to figure out how you can generate a semantic similarity profile from 

https://incatools.github.io/ontology-access-kit/cli.html#runoak-similarity

Using something small, maybe http://purl.obolibrary.org/obo/cl/cl-simple.owl.

The key point is here to get _some_ semantic similarity profile you can use for testing your tool, which uses the correct table format.

**Comment by souzadevinicius** [comment]
Perhaps PR #48 fixes this issue...
