### ISSUE TITLE
Randomize Semantic Similarity Profiles

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/pheval#4]
**Motivation**
We want to study the effect of changes to the semantic similarity profiles on various algorithms including variant prioritisation. To better understand the effects we propose to conduct controlled experiments. As a first pass we will use the current canonical semantic similarity profiles used by exomiser and scramble the similarity to varying degrees (randomisation).

**Procedure**

There are three phenotypic semantic similarity profiles used in exomiser:

- HP_HP_MAPPINGS
- HP_MP_MAPPINGS
- HP_ZP_MAPPINGS

Changes will be made to the following columns:
- SIMJ
- IC
- SCORE

We will produce a python function that takes as input a pandas dataframe with the semantic similarity profile and a value between 0 and 1 (scramble_factor: 0 means no scrambling and 1 means complete randomisation). It then randomises the above scores with a degree of the scramble_factor and returns a scrambles pandas dataframe.

**Comment by matentzn** [comment]
@souzadevinicius thank you for making this issue! Please provide a tiny bit more detail:

1) Why do we do this
2) What values should be scrambled
3) How are we going to "check the effects"

**Comment by souzadevinicius** [comment]
completed in #147
