### ISSUE TITLE
Development of data comparison pipeline for exomiser results

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/pheval#5]
**Motivation**

Exomiser produces, on every run a result in JSON format. We will need to understand how one such result differs from another. The goal of this ticket is twofold, 
1. Understand which values can be meaningfully compared across runs 
2. Provide a basic comparison between those values

**Implementation**

Develop a python function that takes as a input two exomiser JSON result files to produce a analysis file which contains the comparison metrics.
For example, provide a section in the output JSON which has percentage change between the predictive variant score in one run compare to another.
Another example is simply provide the top four genes across each run.

**Comment by matentzn** [comment]
Thank you! Please provide more details about the exact inputs of this first comparison pipeline and a (provisional) [definition of done](https://www.agilealliance.org/glossary/definition-of-done).
