### ISSUE TITLE
Is there a reason we have separate commands for single input and multi input?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#56]
It seems odd to have separate commands every time we want to be able to pass a single element vs a set of elements. Usually, it is better to solve this on option level.

So rather than:

`pheval-utils scramble-phenopacket` / `pheval-utils scramble-phenopackets` 

this is what I usually see:

`pheval-utils scramble-phenopacket --phenopacket filename.json` / `pheval-utils scramble-phenopacket --phenopackets corpus.json` (or directory, doesn't matter).

@yaseminbridges can you explain your design here? Maybe I am wrong about that! :)

**Comment by yaseminbridges** [comment]
This is something that I had roughly come up with @julesjacobsen during a code review a few months ago. My plan was to solve the options at this level as it reduces the amount of duplicated code for defining the click commands - I've already defined a "mutually exclusive" class to deal with options that should not be specified together in other commands and so can do the same with this. I agree that this could be presented a lot cleaner in the way you are suggesting and limits the number of commands being added. This is something that I can work on

**Comment by matentzn** [comment]
I am not that experienced with this, I just wanted to bring it up - maybe google a bit and discuss with Jules, and if you think this is the way to go, I don't mind. I just want to be sure :)
