### ISSUE TITLE
Develop a data comparison between two (phenotypic) semantic similarity profiles

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/pheval#6]
**Motivation**

In order to study the effects of phenotypic semantic similarity profiles we need to first characterize the difference. See also #4 

**Implementation**

Develop a python function as part of a Jupyter notebook that takes as input two pandas dataframes with semantic similarity profiles and analyses how they differ from each other. The metrics to describe this difference need to be developed as a first pass we want to understand what is the average change of all phenotypic similarity values across pairs of ontology classes.
For example, consider SSP1, with N:1,N:2,0.9 and SSP2 with N:1,N:2,0.45 the percentage change is -100% (google it!)

**Testing**

Use the original HPHP mapping table from exomiser and compare it with the scrambled results from #4.

**Comment by matentzn** [comment]
Track: https://github.com/Knowledge-Graph-Hub/semsim/pull/12

**Comment by souzadevinicius** [comment]
Perhaps this issue can be closed after PR #48 merge
