### ISSUE TITLE
Add --version option to `pheval run`

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#67]
As discussed in the last call, we should extend the `pheval run` command with an `--version` option. This option should make it into the main run method. 

It is the implementors job to handle this version, or ignore it, the idea being that they can just switch between different implementations (runners) on the fly. So the users adds --version 13.01 and you, the maintainer, can use this information to direct the execution to a 13.01 specific implementation. This does not affect the input configuration directory (databases etc), which we will assume is compatible with the provided version string.

Does this make sense @yaseminbridges?

**Comment by yaseminbridges** [comment]
Yep, this makes sense!
