### ISSUE TITLE
Provide a schema for the experimental run

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#68]
Every run should result in a bunch of standard results (as @yaseminbridges has already implemented), and a single `results.yml` file that contains metadata about the run. That metadata will be defined in a linkml schema moving forward, but for now, lets make sure the following is outputted with every run:

results.yml
```
tool: exomiser
tool_version: 13.01
config: default
run_timestamp: 1678186600968
corpus: corpus1-default
```

The file con contain other things as well, but I would make these things required.

**Comment by matentzn** [comment]
- [ ] Provide provisional output for existing runners (@yaseminbridges)
- [ ] Create schema (@souzadevinicius) - I will introduce you to the dark art

**Comment by yaseminbridges** [comment]
What would be going into the ```config``` here?

**Comment by matentzn** [comment]
An id that represents the config, like `exomiser-13.01-semsim1` or `exomiser-13.01-semsim1` (basically reflecting the config dir structure as described on the slides). Could be also a path like `exomiser-13.01/semsim1` - up to you. The point is you should be able to understand which config lead to this result.

**Comment by yaseminbridges** [comment]
Understood, thank you!

**Comment by yaseminbridges** [comment]
@matentzn can I just double check, this is something that should be implemented in PhEval and not in all the runner implementations separately?

**Comment by matentzn** [comment]
The basic schema should be in pheval, but there should a special field in the schema like "tool_specific_configuration_options" that can be overwritten to the tool developers hearts content..
