### ISSUE TITLE
Do not include absolute paths in config or result files

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#75]
In order for the pipeline to be portable, config files (`config.yaml`), results files (`results.yml`) and corpus files (`corpus.yml`) should _never include absolute paths_. We need to be able to run the exact pipeline in multiple environments.

There are a few options we can deal with paths.

1. Make sure that our processes (pheval run, etc) only ever have access to the exact directory they are being given by the CLI, nothing else. All files required are in the input-dir. Big files shared across processes are simply symbolic links. This is my preferred option.
2. My less preferred option is to work with environment variables. We can define a environment variable PHEVAL_WORKSPACE which is always available and provides an absolute link to the pheval workspace. Only if necessary.

@yaseminbridges what do you think? What are your concerns with 1?

**Comment by yaseminbridges** [comment]
I don't have any concerns with 1, it is also my preferred option. Just to clarify, when specifying paths in the CLI can these be absolute paths, or would these be relative paths? I think I understand what you want, so instead of having

```
software_directory: /configurations/default_runner-1.0.0/default/default-runner-cli-1.0.0
```

in the config.yaml. It would be something more like:

```
software_directory: default_runner-1.0.0/default/default-runner-cli-1.0.0
```

Likewise when reporting the results.yml, instead of 


```
tool: exomiser
tool_version: 13.2.0
config: /Users/yaseminbridges/full_test_pheval_run/configurations/exomiser-13.2.0/default/config.yaml
run_timestamp: 31
corpus: /Users/yaseminbridges/full_test_pheval_run/corpora/corpus1/default
```

it could be:

```
tool: exomiser
tool_version: 13.2.0
config: exomiser-13.2.0/default
run_timestamp: 31
corpus: corpus1/default
```

**Comment by matentzn** [comment]
For results.yml. thats exactly right!

```
tool: exomiser
tool_version: 13.2.0
config: exomiser-13.2.0/default
run_timestamp: 31
corpus: corpus1/default
```

Is beautiful!

<hr> 

The other case, however:

```
software_directory: /configurations/default_runner-1.0.0/default/default-runner-cli-1.0.0
```

Does not belong in config.md, because config.md is supposed to be exactly in that directory, right?

**Comment by yaseminbridges** [comment]
Yep the config.yaml would be exactly in that directory (`/configurations/default_runner-1.0.0/default/config.yaml`). I think I am a bit confused now as to what is the 'fixed' variables that would be inside it, at the moment I have:

```
tool: defaultrunner
software_directory: /configurations/default_runner-1.0.0/default/default-runner-cli-1.0.0
software_config: /configurations/default_runner-1.0.0/default/software-config.yml
input_directory: /configurations/default_runner-1.0.0/default/
phenotype_only: False
```

so I just have detailed specific paths within the input directory that would need to be used during the `run`. But maybe this isn't necessary? I'm just going off what I have when I download exomiser/phen2gene/lirical to run locally, there is a directory named like `exomiser-cli-13.1.0/` which contains the `.jar` file to run the software. But if the input-dir is not structured in this way it's not necessary for these to be specified in the config.yaml I think

**Comment by matentzn** [comment]
The rule of thumb is:

1. Metadata and _application specific config_ goes in config.md
2. Application general config (aka pheval run parameters) do not go into the config file

Tool name and version should probably go in the config despite being 2.

**Comment by yaseminbridges** [comment]
Got it. So something like this is more optimal?

```
tool: defaultrunner
tool_version: 1.0.0
phenotype_only: False
tool_specific_configuration_options: ....
```

**Comment by yaseminbridges** [comment]
Yep, and it won't create the `pheval_variant_results/` directory in the structure either
