### ISSUE TITLE
Dealing with exomiser application properties

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/pheval#76]
I would prefer this:

1. We provide access to a generic application.properties file in the input-dir
2. Anything we need to set in that file prior to run (data-dir) should be included in the config.yml
3. The exomiser runner itself parses the options that need to be overwritten from the config.yml and rewrites application.properties as needed. 

This isolates all experimental factors of a run into a single file, which is more transparent when interpreting results down the line.

**Comment by yaseminbridges** [comment]
I can expand what I already have in the Exomiser runner (overwriting the data directory path in the application.properties). I think I may have wrapped my head around removing `--config-file` and moving its contents into the config in the input-dir. I am guessing there would be field that could be written in the config.yml by the tool developer and that can be parsed into methods specific to the runner?

**Comment by matentzn** [comment]
> I am guessing there would be field that could be written in the config.yml by the tool developer and that can be parsed into methods specific to the runner?

Exactly! There could be a generic config file reader that loads the whole thing as part of pheval, and then a "getApplicationSpecificConfig()" method that could be used to retrieve them. But note, the developer does not _have_ to use config.yml -> they have their directory, and that has all the files (including config files!) that they want! I just like the transparency coming with adding these parameters to the config.yml file.

**Comment by yaseminbridges** [comment]
Okay, that sounds good! Makes more sense to me now!

**Comment by yaseminbridges** [comment]
I just want to make sure I have the idea in my head right after the last meeting. Should I still be expecting a generic application.properties and editing this in the `--input-dir` or am I generating an application.properties with all the desired fields within the runner?

**Comment by matentzn** [comment]
The latter. You get all the info through config.yml and write your application.properties file yourself!

**Comment by yaseminbridges** [comment]
got it!
