### ISSUE TITLE
Obtain the gene symbol from a gene identifier

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval#79]

**Comment by matentzn** [comment]
How will this be implemented?

If it is not too much to ask (I am fine if it is!) I would like to suggest to standardise all mappings required by pheval outside of pheval, in a mapping commons. I can show you how to do this!

**Comment by yaseminbridges** [comment]
I was planning on extending the [GeneIdentifierUpdator](https://github.com/monarch-initiative/pheval/blob/b0e70e478018ea750c6eb77942068159dd13a77f/src/pheval/utils/phenopacket_utils.py#L244), to include a method that will retrieve the gene symbol given either the NCBI, Ensembl or HGNC id. This is because in the LIRICAL results, the results report the NCBI gene ID only - not a gene symbol and so I can't produce the pheval gene standardised results from this.

But I would be happy to use a mapping commons to standardise all mappings required by pheval outside of pheval, will take you up on your offer!

**Comment by yaseminbridges** [comment]
I can add in what I have for now but I do agree that your idea is the better move forward
