### ISSUE TITLE
Naming of output directories

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval#90]
Definitions:
  'Tool' is a piece of software, e.g. Exomiser, LIRICAL 'exomiser-13.2.0'
  'ToolConfiguration' is a Tool, configured for a specific test case, e.g. a particular data version 'exomiser-13.0.1-2302'
  'Corpus'
  'CorpusVariant'

These follow the naming convention {Tool}-{Configuration} || {Corpus}-{Variant} and the directory layout follows the pattern:

```
{Tool}-{Configuration}
 - {Corpus}-{Variant}
 - {Corpus}-{Variant1}
 - {Corpus1}-{Variant}
 - {Corpus1}-{Variant1}
{Tool}-{Configuration1}
 - {Corpus}-{Variant}
 - {Corpus}-{Variant1}
 - {Corpus1}-{Variant}
 - {Corpus1}-{Variant1}
 ```
e.g.
```
output
├── exomiser-13.2.0-default (a 'ToolConfiguration')
│   └── corpus1-default (a 'CorpusVariant')
│      ├── pheval_gene_results
│      ├── pheval_variant_results
│      ├── tool_input_commands
│      └── results
├── exomiser-13.2.0-semsim1 (a 'ToolConfiguration')
│   └── corpus1-default (a 'CorpusVariant')
│      ├── pheval_gene_results
│      ├── pheval_variant_results
│      ├── tool_input_commands
│      └── results
```

The Makefile needs to  create the {Tool}-{Configuration} and  {Corpus}-{Variant} directories.

The API will 'know' about the internal CorpusVariant directory structure for telling the PhEvalRunner to read and write the results to and where the post-processing happens.

The Analysis command needs to know about the testdata corpus directory `corpora/corpus/corpus-variant` and the corresponding results directory `output/ToolConfiguration/CorpusVariant`, this could be handled by the MakeFile, e.g. a tsv file produced containing records of the testdata directories and the corresponding results directories which is then fed in as an input to `pheval analyse`

**Comment by matentzn** [comment]
@souzadevinicius note this structure - its a tiny bit different from what we originally said:

```
{Tool}
 - {Configuration}-{Corpus}-{Variant}
```

But I cant see any downside with this.
